version: '3.7'
services:
  nginx:
    build: nginx
    ports:
      - "443:443"
    depends_on:
      - web
  web:
    build: web
    expose:
      - 5000
    env_file: .env
    depends_on:
      - db
  db:
    build: db
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=dev
    volumes:
      - ./pgdata:/var/lib/postgresql/data
